"""References: the passive nouns of the DSL.

None of these classes know anything about a Graph. `Node("movie").name` is just
`Attr(node, "name")`; whether "name" is a column or a relation, and what its
label column is, is decided by the Query at compile time. This is the whole
point of moving from `g.node(type)` to a bare `Node(type)`: the reference is
pure syntax, the Query connects it to the graph.

Operators build Conditions (see conditions.py) and never touch the graph, so the
model stays fully lazy: nothing runs until the Query does.
"""

from .core import Ref, Expr, And
from .conditions import Compare, Has, In, Match


class Node(Ref):
    """A pattern variable, optionally typed and pre-constrained by kwargs.

        Node("movie")
        Node("movie", year=1994)          # kwargs are sugar for `.attr == value`
        Node()                            # untyped wildcard (e.g. a path midpoint)

    Attribute access returns an Attr; the Query decides at compile time whether
    that name is a column or a relation -- driven by how the Attr is used, e.g.
    `movie.directed_by == Node("person")` is a relation, `movie.year >= 1990`
    is a column. Two Nodes are distinct variables even if they look identical
    (identity semantics), so reuse the *same* Node object to mean the same
    variable across select/where.
    """

    def __init__(self, type=None, **attrs):
        self.type = type
        self.attrs = attrs        # {name: value} sugar, expanded to Compare at compile
        self._aliases = {}        # queried name -> column, or {type: column}

    def alias(self, **names):
        """Say what a name means on this variable, and get the variable back.

        A graph names its own columns; a query that wants to ask across types
        without knowing them says so here rather than relying on the loader to
        have guessed:

            movie = Node("movie").alias(label="title")
            anything = Node().alias(label={"movie": "title", "person": "name"})

        It annotates rather than clones, because two Nodes are two pattern
        variables and returning a new one would silently split the pattern."""
        self._aliases.update(names)
        return self

    def __getattr__(self, name):
        if name.startswith("_"):
            raise AttributeError(name)
        return Attr(self, name)

    # membership that operators can't express: fluent sugar for the In object.
    def is_in(self, keys):
        """The In condition on this node's identity: bind only to these full keys.
        Fluent equivalent of `In(node, keys)` -- one mechanism, two spellings."""
        return In(self, keys)


class Attr(Expr):
    """A reference to a Node's attribute *or* relation: `node.<name>`.

    Which one it is is never decided here -- it is decided by what you do with
    it:
        node.year >= 1990                 -> Compare  (a column predicate)
        node.title == "Akira"             -> Compare  (a column predicate)
        node.directed_by == Node("person")-> Has      (a relation edge)
        Like(node.title, "akira")         -> Like     (a fuzzy column match)
        select(node.title)                -> projection

    __eq__ is the pivot: a Ref on the right means "relation to that node", any
    other value means "column equals value".

    `.inverse` walks a relation backwards -- `person.directed_by.inverse` is the
    movies a person directed. There is no `directed_by_r`: the reverse of a
    relation is the same relation, and the graph stores it once.

    A name is the column of that name, with no guessing. Two are generated by
    the loader for every type: `.id` is the node's position and `.label` is what
    identifies it outside the graph. To ask one question across types whose
    columns are spelled differently, say so on the variable:

        Like(Node().alias(label="title").label.is_in(names))
    """

    def __init__(self, node, name, reverse=False):
        self.node = node
        self.name = name
        self.reverse = reverse

    @property
    def inverse(self):
        """The same relation, traversed from target to source."""
        return Attr(self.node, self.name, not self.reverse)

    def __eq__(self, other):
        if isinstance(other, Ref):                # relation: node -name-> other
            return Has(self.node, self.name, other, self.reverse)
        return Compare(self, "eq", other)

    def __ne__(self, other):
        return Compare(self, "ne", other)

    def __lt__(self, other):
        return Compare(self, "lt", other)

    def __le__(self, other):
        return Compare(self, "le", other)

    def __gt__(self, other):
        return Compare(self, "gt", other)

    def __ge__(self, other):
        return Compare(self, "ge", other)

    def is_in(self, values):
        """node.<attr> is one of these values (Polars `.is_in`). Softens under
        Like(...) to set similarity."""
        return In(self, values)

    def is_between(self, lower, upper):
        """lower <= node.<attr> <= upper (Polars `.is_between`)."""
        return And(self >= lower, self <= upper)

    def contains(self, text):
        """Crisp substring match on node.<attr> (Polars `.str.contains`, flattened).
        Softens under Like(...) to fuzzy similarity."""
        return Compare(self, "contains", text)

    def count(self):
        """The relation's arity as a scalar expression: `node.directed_by.count()`.
        Usable as a predicate (`>= 2`), a projection, or a rank signal."""
        return Degree(self.node, self.name, self.reverse)

    # Attr is used as a dict-ish key inside the compiler; keep hashing by identity
    # even though __eq__ is overloaded to build a Condition.
    __hash__ = object.__hash__


class Edge(Ref):
    """A relation marker for path patterns: `Edge("directed_by")`, or `Edge()`
    for a wildcard. Edges are how traversal is written when you prefer an
    explicit path over the `attr == Node(...)` relation form; both compile to
    the same edge in the IR.

    Direction: a named Edge walks source -> target, and `.inverse` walks it the
    other way. The wildcard `Edge()` walks *both* directions -- which is what a
    two-hop pattern like [movie, Edge(), attribute, Edge(), movie] needs, and
    what the old `rv=True` edge duplication was there to fake.

    An Edge has identity semantics like a Node, and for the same reason: naming
    it is what lets a condition elsewhere in the query talk about it.

        watched = Edge("has_interact")
        where(path == [user, watched, rec], watched.score >= 3)

    `score` is the weight the edge carries in the data -- a rating, a similarity,
    a count -- and constraining it is how a graph keeps every edge while a query
    walks only some of them. `Edge("has_interact", score=(3, 5))` is sugar for
    exactly the same conditions, the way `Node("movie", year=1994)` is sugar for
    `movie.year == 1994`."""

    def __init__(self, *relations, reverse=False, score=None):
        self.relations = relations   # empty tuple = wildcard
        self.reverse = reverse
        self.filters = _score_filters(self, score)   # sugar, expanded at compile

    @property
    def inverse(self):
        edge = Edge(*self.relations, reverse=not self.reverse)
        edge.filters = [_rebind(f, edge) for f in self.filters]
        return edge

    @property
    def score(self):
        """The edge's stored weight, as a scalar expression to compare on."""
        return EdgeScore(self)


class EdgeScore(Expr):
    """The weight of the edge an `Edge` marker matches: `edge.score >= 3`.

    Compares like any other Expr -- the operators build a Compare, and the Query
    turns it into an admission mask over stored edges, the exact counterpart of
    the mask a Node constraint becomes.

    `.norm()` reads the same weight rescaled to [0, 1] within its relation. The
    stored score is an unbounded float, which is right for saying what the data
    says and useless for anything that has to accumulate one -- a beam search
    summing steps, a threshold you want to mean the same thing on two relations.
    Normalizing is that translation, and it is explicit because it is lossy."""

    def __init__(self, edge, normalized=False):
        self.edge = edge
        self.normalized = normalized

    def norm(self):
        """The same weight, min-max rescaled inside its own relation."""
        return EdgeScore(self.edge, True)

    # aggregates over every edge this marker matched; see Aggregate
    def sum(self):
        return Sum(self)

    def count(self):
        return Count(self)

    def mean(self):
        return Mean(self)

    def min(self):
        return Min(self)

    def max(self):
        return Max(self)

    def __eq__(self, other):
        return Compare(self, "eq", other)

    def __ne__(self, other):
        return Compare(self, "ne", other)

    def __lt__(self, other):
        return Compare(self, "lt", other)

    def __le__(self, other):
        return Compare(self, "le", other)

    def __gt__(self, other):
        return Compare(self, "gt", other)

    def __ge__(self, other):
        return Compare(self, "ge", other)

    __hash__ = object.__hash__


class Aggregate(Expr):
    """A quantity read off the matches, rather than off the graph.

        rank(Sum(carried.score))     # how much of the pattern's weight a row carries
        rank(Count(tag))             # how many distinct tags reached it

    This is the sibling `Degree` has been missing. `node.rel.count()` counts a
    node's edges in the *graph*, always the same number whatever the query asked;
    an Aggregate counts what *this* pattern matched, which is the question a
    two-hop recommendation actually asks: not "does this share a tag?" but "how
    much of the list is it?".

    A pattern edge matches once per walk, so a result reached five ways is five
    rows. An Aggregate is what folds them: it groups the rows by the columns you
    selected, computes one value per group, and the result carries one row per
    group -- selecting is grouping, the way it is in a spreadsheet and not the
    way it is in SQL, because there is nothing else a projection could mean here.

    `over` is either an EdgeScore -- every edge that marker matched -- or a Node
    of the pattern, whose distinct bindings are what there is to count. Only
    Count takes a Node: the others need a number, and a node is not one.

    Aggregates go in `rank(...)`; `select(..., Score())` reads the value back,
    normalized with every other signal, exactly as it reads back any ranking.
    """

    how = None

    def __init__(self, over):
        self.over = over

    def __repr__(self):
        return f"{type(self).__name__}({self.over!r})"

    __hash__ = object.__hash__


class Sum(Aggregate):
    how = "sum"


class Count(Aggregate):
    """How many matches -- distinct bindings of a Node, or edges of a marker."""
    how = "count"


class Mean(Aggregate):
    how = "mean"


class Min(Aggregate):
    how = "min"


class Max(Aggregate):
    how = "max"


def score_bounds(score):
    """The `score=` kwarg as (op, value) pairs: a pair is an inclusive band (None
    leaves a side open), a bare value is equality -- the reading Node(**attrs)
    gives its kwargs.

    One function rather than two because `Edge(score=...)` and `Has(..., score=...)`
    must mean the same thing, and the surest way to keep two spellings from
    drifting is to leave them nothing of their own to drift with."""
    if score is None:
        return []
    if isinstance(score, (tuple, list)):
        low, high = score
        return [(op, value) for op, value in (("ge", low), ("le", high)) if value is not None]
    return [("eq", score)]


def _score_filters(edge, score):
    """The kwarg as the conditions it stands for, so the sugar and the explicit
    `edge.score >= 3` compile through one path."""
    return [Compare(EdgeScore(edge), op, value) for op, value in score_bounds(score)]


def _rebind(filter_, edge):
    """The same score condition, aimed at another Edge marker (`.inverse` is a
    new variable, and its constraints have to follow it there)."""
    return Compare(EdgeScore(edge, filter_.left.normalized), filter_.op, filter_.value)


class Path(Ref):
    """A variable bound to a whole walk (nodes + the concrete relations between
    them). Constrained by equating it to a pattern list:

        path == [rec, Edge(), seed]                       # rec -*-> seed
        path == [rec, Edge(), Node(), Edge(), seed]       # a 2-hop bridge

    `path == [...]` returns a Match condition; two Matches OR together for
    alternative shapes. path[0] / path[-1] (or .first / .last) reference a node
    inside the walk, itself projectable to an attribute.
    """

    def __eq__(self, pattern):
        return Match(self, pattern)

    def __getitem__(self, index):
        return PathStep(self, index)

    def __getattr__(self, name):
        if name.startswith("_"):
            raise AttributeError(name)
        if name == "first":
            return PathStep(self, 0)
        if name == "last":
            return PathStep(self, -1)
        raise AttributeError(name)

    __hash__ = object.__hash__


class PathStep(Ref):
    """A node position inside a Path (path[-1], path.first). Projectable as-is,
    or narrowed to an attribute: `path.last.title`."""

    def __init__(self, path, index):
        self.path = path
        self.index = index

    def __getattr__(self, name):
        if name.startswith("_"):
            raise AttributeError(name)
        return PathStepAttr(self.path, self.index, name)


class PathStepAttr(Ref):
    """An attribute of a node inside a Path: `path.last.title`."""

    def __init__(self, path, index, name):
        self.path = path
        self.index = index
        self.name = name


class Degree(Expr):
    """The arity of a node's relation as a scalar expression: `node.rel.count()`.

    One expression, three uses -- like a Polars expression across select/filter/
    agg -- but all three are the *expression* role, not a blur of families:
        select(rec.has_interact.inverse.count())       # projection
        where(rec.has_interact.inverse.count() >= 5)   # Compare condition
        rank(rec.has_interact.inverse.count())         # rank signal (Strategy adapter)

    Comparisons build a Compare like any other Expr; the Query knows a Compare on
    a Degree is structural (counted against the graph) rather than a stored attr.
    Using a Degree in rank(...) wraps it in a trivial Strategy that scores by the
    count (see strategies.ExprStrategy).
    """

    def __init__(self, node, relation, reverse=False):
        self.node = node
        self.relation = relation
        self.reverse = reverse

    def __eq__(self, other):
        return Compare(self, "eq", other)

    def __ne__(self, other):
        return Compare(self, "ne", other)

    def __lt__(self, other):
        return Compare(self, "lt", other)

    def __le__(self, other):
        return Compare(self, "le", other)

    def __gt__(self, other):
        return Compare(self, "gt", other)

    def __ge__(self, other):
        return Compare(self, "ge", other)

    __hash__ = object.__hash__
